openapi: 3.0.2
info:
  title: Utilizations (Bills&Collections)
  version: 1.0.2
  description: >-
    The utilizations business API allows  public user to perform different kinds of actions with in
    the  utilizations (bills and collections) context .
  contact:
    name: Rakesh Pai
    url: 'https://rabobank.com/api/'
    email: Rakesh.Pai@rabobank.com
  x-audience: external-public
  x-api-id: 023c6c49-de20-431d-ad36-8ce18ff94681
paths:
  '/clients/{client-id}/utilizations':
    post:
      summary: Create utilization
      operationId: createUtilization
      tags:
        - Utilization
      requestBody:
        description: Create a new utilization with the given details
        content:
          application/json;version=1.0.0:
            schema:
              $ref: '#/components/schemas/UtilizationRequest'
        required: true
      responses:
        '201':
          description: 'Contract created successfully, no content is returned in body, only a reference regarding the created resource is sent within a header'
          headers:
            Content-Location:
              description: Reference to the newly created resource
              required: true
              schema:
                type: string
        '400':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Input missing / Validation failed.
        '401':
          description: Not authorized.
        '403':
          description: "Given credentials are not valid\npatching this value is not allowed. "
        '405':
          description: Method Not Allowed
        '406':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Respones can't served with requested media type.
        '415':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Request with unsupported media type.
        '500':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal Server Error - error during prozessing of request
    get:
      summary: Get list of utilizations
      operationId: getUtilizationList
      tags:
        - Utilization
      responses:
        '200':
          description: 'Retrieve list of utilizations'
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/UtilizationList'
        '400':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Input missing / Validation failed.
        '401':
          description: Not authorized.
        '403':
          description: "Given credentials are not valid\npatching this value is not allowed. "
        '405':
          description: Method Not Allowed
        '406':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Respones can't served with requested media type.
        '500':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal Server Error - error during prozessing of request
      parameters:
        -
          examples:
            LC-reference:
              value: HKGML0119070A2IH
          name: lc_reference
          schema:
            type: string
          in: query
          description: Restrict results to those having this letter of credit as parent reference
          required: true
          allowEmptyValue: false
    parameters:
      -
        examples:
          Client-ID:
            value: 902019395
        name: client-id
        description: ID of an GCDS contact
        schema:
          type: string
        in: path
        required: true
      -
        examples:
          Rabobank-Flow-ID:
            value: WORKFLOW_WorkflowUser_123456789_1514764799
        name: Rabobank-Flow-ID
        description: external identifier that is handed over to FCUBS for traceability
        schema:
          type: string
        in: header
        required: true
 
  '/clients/{client-id}/utilizations/{contract-reference-number}':
    get:
      summary: Get a single utilization
      operationId: getUtilization
      tags:
        - Utilization
      responses:
        '200':
          description: 'Retrieve a single utilization in detail'
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/UtilizationResponse'
        '400':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Input missing / Validation failed.
        '401':
          description: Not authorized.
        '403':
          description: "Given credentials are not valid\npatching this value is not allowed. "
        '404':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Resource not found.
        '405':
          description: Method Not Allowed
        '406':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Respones can't served with requested media type.
        '500':
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal Server Error - error during prozessing of request
    parameters:
      -
        examples:
          Client-ID:
            value: 902019395
        name: client-id
        description: ID of an GCDS contact
        schema:
          type: string
        in: path
        required: true
      -
        examples:
          Rabobank-Flow-ID:
            value: WORKFLOW_WorkflowUser_123456789_1514764799
        name: Rabobank-Flow-ID
        description: external identifier that is handed over to FCUBS for traceability
        schema:
          type: string
        in: header
        required: true
      -
        examples:
          Reference-Number:
            value: HKGMB0119070A2FH
        name: contract-reference-number
        description: Refrence number of a utilization
        schema:
          type: string
        in: path
        required: true
components:
  schemas:
    UtilizationRequest:
      title: UtilizationRequest
      description: Input values - Utilization
      type: object
      required:
        - related_reference_no
        - amount
        - currency
      properties:
        related_reference_no:
          description: Reference number of the letter of credit **(21)**
          type: string
        discrepancies:
          description: AccFate.advftrecpart ADVFTRECPART **(77J)**
          maxLength: 100
          type: string
        value_date_at:
          description: |-
            valdt_at VALDT **(32A)**
            Format : "yyyy-MM-dd"
          type: string
          format: date
          pattern: >-
            2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        amount:
          description: bill_amount AMOUNT Amount of Utilization **(32A)**
          format: decimal
          type: number
        currency:
          description: currency CURRENCY Currency of Utilization **(32A)**
          maxLength: 3
          type: string
        shipment_details:
          $ref: '#/components/schemas/ShipmentDetails'
      example:
        related_reference_no: 'HKGML0119070A2IH'
        discrepancies: ''
        value_date_at: '2020-10-20'
        amount: 34500.99
        currency: 'USD'
        shipment_details:
          loading_place: 'Vancouver'
          delivery_place: 'Hamburg'
          transportation_at: '2019-12-30'
    ShipmentDetails:
      title: ShipmentDetails
      description: Detailed imformation about the destinations and timing
      type: object
      properties:
        loading_place:
          description: Shipment.desfrom
          maxLength: 100
          type: string
        delivery_place:
          description: Shipment.desto
          maxLength: 100
          type: string
        transportation_at:
          description: Shipment.shipdt_at
          maxLength: 100
          type: string
      example:
        loading_place: 'Vancouver'
        delivery_place: 'Hamburg'
        transportation_at: '2019-12-30'
    UtilizationResponse:
      title: UtilizationResponse
      description: Detailed data set of a utilization
      type: object
      properties:
        amount:
          description: bill_amount AMOUNT Amount of Utilization **(32A)**
          format: decimal
          type: number
        currency:
          description: currency CURRENCY Currency of Utilization **(32A)**
          maxLength: 3
          type: string
        value_date_at:
          description: |-
            valdt_at VALDT **(32A)**
            Format : "yyyy-MM-dd"
          type: string
          format: date
          pattern: >-
            2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
      example:
        amount: 68000.00
        currency: 'USD'
        value_date_at: '2019-12-15'
    UtilizationList:
      title: UtilizationListEntry
      description: Basic data set of a utilization
      type: object
      properties:
        contracts:
          type: array
          items:
            $ref: '#/components/schemas/UtilizationListEntry'
    UtilizationListEntry:
      title: UtilizationListEntry
      description: Basic data set of a utilization
      type: object
      properties:
        reference_number:
          description: Reference number of the utilization
          type: string
        amount:
          format: decimal
          description: Amount of the referred utilization
          type: number
        currency:
          description: Currency of the referred utilization
          type: string
      example:
        reference_number: 'HKGMB0119070A2FH'
        amount: 41000.50
        currency: 'USD'
    Error:
      description: Error and Exception reprensentation.
      type: object
      properties:
        error_code:
          description: '6-digit system internal error code, for issue handling with Rabobank'
          type: string
        error_type:
          description: Description of what kind of error occured
          type: string
        error_display:
          description: Enriched error description for the enduser
          type: string
        error_message:
          type: string
          description: Technical error description
      example:
        error_code: WSR006
        error_type: Fault
        error_display: Contract HKGML0666070A2IX does not exist
        error_message: validation.response.status.unknown
    Errors:
      description: Error and Exception reprensentation.
      type: object
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'
      example:
        errors:
          -
            error_code: WSR006
            error_type: Fault
            error_display: Contract HKGML0666070A2IX does not exist
            error_message: validation.response.status.unknown
tags:
  -
    name: Utilization
    description: Utilization operation
