---
openapi: 3.0.2
info:
  title: Letter Of Credit (OpenAPI 3.0.2)
  version: 0.5.0
  description: The Letter of Credit business API allows  public user to perform different
    kinds of actions with in the  import/export letter context .
  contact:
    name: Bram Bergshoeff
    url: https://rabobank.com/api/
    email: Bram.Bergshoeff@rabobank.com
servers:
- url: https://rabobank.com/
  description: Rabobank production system
paths:
  /clients/{clientId}/lettersOfCredit:
    post:
      requestBody:
        content:
          application/json;version=1.0.0:
            schema:
              $ref: '#/components/schemas/LetterOfCredit'
        required: true
      tags:
      - LetterOfCredit
      responses:
        "204":
          headers:
            Content-Location:
              $ref: '#/components/headers/Content-Location'
          description: Resource created.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "401 Error":
                  value:
                  - error_code: WSR410
                    error_type: Fault
                    error_message: Authorization failed.
          description: Input missing / Validation failed.
        "401":
          description: Not authorized.
        "405":
          description: Method Not Allowed
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "405 Error":
                  value:
                  - error_code: WSR415
                    error_type: Fault
                    error_message: Unsupported Media Type.
          description: Unsupported Media Type - Returned if version or response content
            type isn't available.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "500 Error":
                  value:
                  - error_code: WSR500
                    error_type: Error
                    error_message: Server error! Please try again.
          description: Internal Server Error - error during prozessing of request
      summary: Create Letter of Credit
      description: Endpoint with the the facility to create a Letter of Credit resource
        with in the Rabobank system.
    parameters:
    - examples:
        Client UUID:
          value: 24e67f63-5b9a-4c71-b206-d1e5511f7037
      name: clientId
      description: UUID of an GCDS contact
      schema:
        type: string
      in: path
      required: true
    - examples:
        X-MSGID:
          value: WORKFLOW_WorkflowUser_123456789_1514764799
      name: X-MSGID
      description: external identifier that is handed over to FCUBS for traceability
      schema:
        type: string
      in: header
      required: true
  /clients/{clientId}/lettersOfCredit/{contractreferencenumber}:
    get:
      tags:
      - LetterOfCredit
      responses:
        "200":
          content:
            application/json;version=1.0.0:
              schema:
                $ref: '#/components/schemas/LetterOfCreditResponse'
          description: Provide the letter of credit resource.
        "401":
          description: Not authorized.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "405 Error":
                  value:
                  - error_code: WSR404
                    error_type: NotFound.
                    error_message: Letter of credit not found.
          description: Resource not found.
        "405":
          description: Method Not Allowed
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "405 Error":
                  value:
                  - error_code: WSR415
                    error_type: Fault
                    error_message: Unsupported Media Type.
          description: Unsupported Media Type - Returned if version or response content
            type isn't available.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "500 Error":
                  value:
                  - error_code: WSR500
                    error_type: Error
                    error_message: Server error! Please try again.
          description: Internal Server Error - error during prozessing of request
      summary: Get letter of credit
      description: Endpoint to get detailed information of an single  letter of credit
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LetterOfCreditUpdateRequest'
            examples:
              LC Patch request:
                value:
                  currency: EUR
                  amount: 4.400000053E7
                  issued_at: 2019-12-16T16:06:05.000Z
                  expired_at: 2020-05-30T16:06:05.000Z
                  product_code: ML01
                  shipment:
                    from: Rio de Janeiro
                    to: Hamburg
                    partial: true
                    transferable: true
                    period: comment ...
                  participants:
                    advising_bank: Cooperatieve Rabobank
                    beneficiary: TRADE CUST 01
                    applicant: TRADE CUST 02
        required: true
      tags:
      - LetterOfCredit
      responses:
        "200":
          description: Import LC was updated successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "401 Error":
                  value:
                  - error_code: WSR410
                    error_type: Fault
                    error_message: Authorization failed.
          description: Input missing / Validation failed.
        "401":
          description: Not authorized.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "401 Error":
                  value:
                  - error_code: WSR404
                    error_type: Fault
                    error_message: No content found for this client.
          description: Resource not found.
        "405":
          description: Method Not Allowed
        "415":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "405 Error":
                  value:
                  - error_code: WSR415
                    error_type: Fault
                    error_message: Unsupported Media Type.
          description: Unsupported Media Type - Returned if version or response content
            type isn't available.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                "500 Error":
                  value:
                  - error_code: WSR500
                    error_type: Error
                    error_message: Server error! Please try again.
          description: Internal Server Error - error during prozessing of request
      summary: Update/modify letter of credit
      description: Endpoint to update/modify a letter of credit with in the Rabobank
        system
    parameters:
    - examples:
        Client UUID:
          value: "24e67f63-5b9a-4c71-b206-d1e5511f7037\t\r\n"
      name: clientId
      description: UUID of an GCDS contact
      schema:
        type: string
      in: path
      required: true
    - examples:
        Import LC UUID:
          value: 5cdb034c-f67f-453f-9ae8-b125c3d64372
      name: contractreferencenumber
      description: UUID of an existing import LC
      schema:
        type: string
      in: path
      required: true
    - examples:
        X-MSGID:
          value: WORKFLOW_WorkflowUser_123456789_1514764799
      name: X-MSGID
      description: external identifier that is handed over to FCUBS for traceability
      schema:
        type: string
      in: header
      required: true
components:
  schemas:
    LetterOfCredit:
      title: ImportLetterOfCredit
      description: ImportLetterOfCredit
      required:
      - amount
      - currency
      - product_code
      - product_type
      - issued_at
      - expired_at
      - shipment
      - participants
      - goods
      type: object
      properties:
        currency:
          description: Assiged currency to the amount
          maxLength: 3
          minLength: 3
          pattern: '[A-Z]{3}'
          type: string
        amount:
          format: double
          description: Amount of the guaranteed payment between buyer/seller.
          type: number
        product_code:
          description: |-
            Definition for the way of commission.
            Options:
            ML01 - "Import LC issuance - Non Revolving - Commission in advance"
            Ml02 - "Import LC issuance - Non Revolving - Commission in arrears"
          maxLength: 4
          minLength: 4
          pattern: '[A-Z0-9]{4}'
          enum:
          - ML01
          - ML02
          type: string
        product_type:
          description: "Definition of the LC kind. \nOptions:\nI - \"Import letter\"\
            \nE - \"Export letter\""
          maxLength: 1
          minLength: 1
          enum:
          - I
          - E
          type: string
        shipment:
          $ref: '#/components/schemas/Shipment'
          description: Detailed location and timing information about the shipment
            of the goods.
        expired_at:
          format: date-time
          description: "Specify the expiry date for the facility. If the limit amount\
            \ assigned to the facility is not utilized within the specified expiry\
            \ date then the Available check box will remain un-selected. This freezes\
            \ the line for the respective liability. \r\nISO8601 based date format(\"\
            yyyy-MM-dd'T'HH:mm:ssZ\")."
          pattern: 2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z
          type: string
        issued_at:
          format: date-time
          description: |
            The letter of credit issue date.
            ISO8601 based date format(("yyyy-MM-dd'T'HH:mm:ssZ")).
          pattern: 2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z
          type: string
        participants:
          $ref: '#/components/schemas/Participants'
          description: Information of engaged trade parties.
        goods:
          description: Detailed list of goods that are part of the shipment with in
            the context of the LC.
          type: array
          items:
            $ref: '#/components/schemas/Good'
      example:
        product_type: I
        product: ML01
        currency: EUR
        amount: 4.400000053E7
        issued_at: 2019-12-16T16:06:05.000Z
        expired_at: 2020-05-30T16:06:05.000Z
        product_code: ML01
        shipment:
          from: Rio de Janeiro
          to: Hamburg
          partial: true
          transferable: true
          latest_shipment_at: 2020-03-30T16:06:05.000Z
          period: comment ...
        participants:
          advising_bank: Cooperatieve Rabobank
          beneficiary: TRADE CUST 01
          applicant: TRADE CUST 02
        goods:
        - description: Crude oil - 2Bseen
          units: 10 BBL
          unitPrice: 55.4
    Error:
      description: Error and Exception reprensentation.
      type: object
      properties:
        error_code:
          description: 6-digit system internal error code, for issue handling with
            Rabobank
          type: string
        error_type:
          description: Description of what kind of error occured
          type: string
        error_message:
          description: Enriched error description for the enduser
          type: string
      example:
        error_code: WSR006
        error_type: Fault
        error_message: Customer Number 2128 does not exist
    ErrorList:
      description: Error and Exception reprensentation.
      type: array
      items:
        $ref: '#/components/schemas/Error'
      example:
      - error_code: WSR006
        error_type: Fault
        error_message: Customer Number 2128 does not exist
    LetterOfCreditUpdateRequest:
      title: LetterOfCreditUpdateRequest
      description: ""
      type: object
      properties:
        currency:
          description: Assiged currency to the amount
          maxLength: 3
          minLength: 3
          pattern: '[A-Z]{3}'
          type: string
        amount:
          format: double
          description: Letter of credit amount
          type: number
        issued_at:
          format: date-time
          description: |
            The letter of credit issue date.
            ISO8601 based date format(("yyyy-MM-dd'T'HH:mm:ssZ")).
          pattern: 2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z
          type: string
        expired_at:
          format: date-time
          description: "Specify the expiry date for the facility. If the limit amount\
            \ assigned to the facility is not utilized within the specified expiry\
            \ date then the Available check box will remain un-selected. This freezes\
            \ the line for the respective liability. \r\nISO8601 based date format(\"\
            yyyy-MM-dd'T'HH:mm:ssZ\")."
          pattern: 2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z
          type: string
        product_code:
          description: |-
            ML01 - "Import LC issuance - Non Revolving - Commission in advance"
            or
            Ml02 - "Import LC issuance - Non Revolving - Commission in arrears"
          maxLength: 4
          minLength: 4
          pattern: '[A-Z0-9]{4}'
          enum:
          - ML01
          - ML02
          type: string
        shipment:
          $ref: '#/components/schemas/Shipment'
          description: Shipment details of letter of credit.
        participants:
          $ref: '#/components/schemas/Participants'
          description: Information of engaged trade parties.
      example:
        currency: EUR
        amount: 4.400000053E7
        issued_at: 2019-12-16T16:06:05.000Z
        expired_at: 2020-05-30T16:06:05.000Z
        product_code: ML01
        shipment:
          from: Rio de Janeiro
          to: Hamburg
          partial: true
          transferable: true
          latest_shipment_at: 2020-03-30T16:06:05.000Z
          period: comment ...
        participants:
          advising_bank: Cooperatieve Rabobank
          beneficiary: TRADE CUST 01
          applicant: TRADE CUST 02
    LetterOfCreditResponse:
      title: LetterOfCreditResponse
      description: ""
      required:
      - product_type
      - product
      - currency
      - amount
      - expired_at
      - authorized
      type: object
      properties:
        product_type:
          description: ""
          enum:
          - I
          - E
          type: string
        product:
          description: ""
          enum:
          - ML01
          - ML02
          type: string
        currency:
          description: ""
          type: string
        amount:
          format: double
          description: ""
          type: number
        authorized:
          description: ""
          type: boolean
        expired_at:
          format: date-time
          description: ""
          type: string
      example:
        product_type: I
        product: ML01
        currency: EUR
        amount: 4.0000000005E9
        expired_at: 2020-05-30T16:06:05.000Z
        authorized: true
    Good:
      title: Good
      description: Detailed list of goods that are part of the shipment with in the
        context of the LC.
      type: object
      properties:
        description:
          maxLength: 65
          type: string
        units:
          maxLength: 65
          type: string
        unitPrice:
          format: double
          type: number
      example:
        description: Crude oil - 2Bseen
        units: 10 BBL
        unitPrice: 55.4
    Participants:
      title: Participants
      description: Information of engaged trade parties.
      required:
      - advising_bank
      - applicant
      - beneficiary
      type: object
      properties:
        advising_bank:
          description: Trade party
          maxLength: 100
          type: string
        beneficiary:
          description: Trade party
          maxLength: 100
          type: string
        applicant:
          description: Trade party
          maxLength: 100
          type: string
      example:
        advising_bank: Cooperatieve Rabobank
        beneficiary: TRADE CUST 01
        applicant: TRADE CUST 02
    Shipment:
      description: Detailed location and timing information about the shipment of
        the goods.
      required:
      - latest_shipment_at
      - period
      type: object
      properties:
        transferable:
          description: |-
            Indicates if an transferable shipment is allowed.
            (Default: false)
          default: false
          type: boolean
        partial:
          description: "Indicates if partial shipment is allowed \r\n(Default: false)"
          default: false
          type: boolean
        from:
          description: Place of taking goods in Charge / Place of receipt
          maxLength: 65
          type: string
        to:
          description: Place of final destination / Place of delivery
          maxLength: 65
          type: string
        latest_shipment_at:
          format: date-time
          description: "Latest point in time for the shipment. \nFormat : \"yyyy-MM-dd'T'HH:mm:ssZ\""
          pattern: 2[0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]Z
          type: string
        period:
          description: Shipment period
          maxLength: 395
          type: string
        loading_port:
          description: Airport of loading the goods
          maxLength: 65
          type: string
        discharge_port:
          description: Airport to discharge the goods
          maxLength: 65
          type: string
      example:
        from: Rio de Janeiro
        to: Hamburg
        partial: true
        transferable: true
        period: comment ...
  headers:
    Content-Location:
      schema:
        type: string
      example: /contacts/90fd3870-75d6-4eb8-ae6d-2216f201c28f/importLettersOfCredit/90fd3870-75d6-4eb8-ae6d-2216f201c28f
      description: Path to the created resource.
tags:
- name: LetterOfCredit
  description: Letter Of Credit operation
